sudo: false

language: go

go:
  - '1.12.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules


jobs:
  include:
    - stage: docs build
      if: type != pull_request
      script:
        - sh build/bin/trigger-docs-travis $TRAVIS_API_TOKEN
    - stage: build
      script: make build

    - stage: push images
      if: type != pull_request
      script:
        - bash ./build/bin/push-images
